name: BlockCanBuildEvent
description: In this example we implement new ways to get charcoal by burning wood objects.
version: 0.1
author: Ugleh
main: com.ugleh.eventexamples.blockcanbuildevent.BlockCanBuildEventExample
api-version: 1.13
